version: "3.7"

services:
  camera:
    env_file:
      - .env

    build:
      context: .
    image: camera
    container_name: camera

    # Persist data across redeploys
    volumes:
      - "camera_storage:/rails/storage"
      - "camera_hls:/rails/public/hls"

    restart: always

    labels:
      - "traefik.enable=true"

      # Only volleycam.com
      - "traefik.http.routers.camera.rule=Host(`volleycam.com`)"
      - "traefik.http.routers.camera.entrypoints=websecure"
      - "traefik.http.routers.camera.tls.certresolver=production"

      # Internal container port
      - "traefik.http.services.camera.loadbalancer.server.port=80"

    networks:
      - traefik

    depends_on:
      - db

  db:
    image: postgres:16
    container_name: camera_db
    restart: always
    env_file:
      - .env
    volumes:
      - "camera_db:/var/lib/postgresql/data"

volumes:
  camera_storage:
  camera_hls:
  camera_db:

networks:
  traefik:
    external: true
